### ISSUE TITLE
node环境中，ReferenceError: window is not defined

### ISSUE THREAD

**Issue by vlev1n** [theajack/cnchar#2]
index.js
```javascript
const CnChar = require('cnchar')
```
运行`node index.js`
```
D:\vanilla\node_modules\cnchar\lib\cnchar.js:129
  window.CnChar={
  ^

ReferenceError: window is not defined
    at D:\vanilla\node_modules\cnchar\lib\cnchar.js:129:3
    at Object.<anonymous> (D:\vanilla\node_modules\cnchar\lib\cnchar.js:146:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\vanilla\node_modules\cnchar\lib\index.js:1:80)
```

自1.0.3起出现此问题

**Comment by theajack** [comment]
我来看看，谢谢你的提醒

**Comment by theajack** [comment]
已修复，请更新到1.0.5
